### ISSUE TITLE
Add feature: Multiple file saving formats

### ISSUE THREAD

**Issue by harleo** [harleo/knockknock#1]
I'm looking for some(one) to add different file saving formats to the codebase.

For example:
- TXT
- Other formats; If you have more format ideas please share them.

If you'd like to help, please comment below and commit to the "dev" branch.

Thanks :)

**Comment by Ranc58** [comment]
Hi @harleo!
Can i help you with this issue?
I would add `txt` support. And what you think about `xlsx`?

**Comment by harleo** [comment]
> Hi @harleo!

Hey @Ranc58 :)

> Can i help you with this issue?

Sure go ahead!

> I would add `txt` support. And what you think about `xlsx`?

Sounds good.
Do you need any additional dependencies for xlsx?
I'd like to limit the requirements to the bare minimum.

Thanks for helping!

**Comment by Ranc58** [comment]
Yes, for xlsx we need for example `openpyxl`.
Ok, If you want to keep the minimum requirements count - i'll add only `txt` support for now)

**Comment by harleo** [comment]
> Yes, for xlsx we need for example `openpyxl`.
> Ok, If you want to keep the minimum requirements count - i'll add only `txt` support for now)

Спасибо ))
