### ISSUE TITLE
No results after the latest update

### ISSUE THREAD

**Issue by sumgr0** [harleo/knockknock#11]
Hey man!

After updating to the latest update no results are discovered, using domain name or even email address.

![image](https://user-images.githubusercontent.com/11391119/178409691-6ae17bdf-e933-4623-92a5-44a8f8f3b644.png)

Hope this can be fixed soon. Thanks

**Comment by harleo** [comment]
Hey @sumgr0 sorry for the delay.

Have you tried reinstalling it with `go install github.com/harleo/knockknock@latest` after the update? 
Make sure to remove the binary if you have built it previously in `/go/bin`.

```bash
$ ./knockknock -n google.com -p
[:] Sending query...
028-hty.com | 2016-05-20 | DROPCATCH.COM 883 LLC
04plan.com | 2020-04-04 | GABIA, INC.
0512zc.cn | 2007-03-10 |
[...]
```

**Comment by sumgr0** [comment]
Hi Leo,

Apologies for the late reply, but even after removing the old binary and 
reinstalling the tool, its not working for me:

$ rm -rf $(which knockknock)
$ go install ***@***.***
go: downloading github.com/harleo/knockknock 
v0.0.0-20220709155934-e9a2bccb18f1
go: finding module for package github.com/PuerkitoBio/goquery
go: found github.com/PuerkitoBio/goquery in 
github.com/PuerkitoBio/goquery v1.8.0
go: downloading golang.org/x/net v0.0.0-20210916014120-12bc252f5db8
$ knockknock -n google.com -p
[:] Sending query...
[!] No domains found
[:] Done.



Best,

Sumit Grover
Security Enthusiast
Twitter: @sumgr0

**Comment by harleo** [comment]
@sumgr0 It might be that you're being rate limited. Have you tried from a different IP? The tool currently doesn't catch that case.

**Comment by sumgr0** [comment]
@harleo, tried it on another box and got the same error/no results.

Best,

Sumit Grover
Security Enthusiast
Twitter: @sumgr0

**Comment by harleo** [comment]
@sumgr0 could you check if it is fixed with the latest update? I added a check for when Cloudflare blocks the query because it may check for cloud IPs and requires a captcha verification.

If the result is still the same, could you `git clone` the repository and run it directly with `go run k2.go -n google.com -p` and report back the output?

Thanks for the help.

**Comment by sumgr0** [comment]
@harleo,

Looks like the Cloudflare is blocking the IP.

knockknock -n google.com -p
[:] Sending query...
[!] Query was blocked by Cloudflare captcha, try from a different IP.


Best,

Sumit Grover
Security Enthusiast
Twitter: @sumgr0

**Comment by harleo** [comment]
@sumgr0 Thanks for checking! Unfortunately I can't do anything about it, unless we find another free alternative. I found that residential IPs work.

Closing for now.
