### ISSUE TITLE
to phones, emails, ?

### ISSUE THREAD

**Issue by darknodi** [harleo/knockknock#8]
@harleo @raylu @Ranc58

**Comment by harleo** [comment]
Hey @darknodi, could you elaborate a bit more what you are asking for?

**Comment by darknodi** [comment]
in the github.com 
there many developers which have published these scenarious for different aimings.

i have aimed to use bash, to make one menu scenarious, for listed all scenarious scriptings, in one menu. with inserted scenarious from github.com developers, in one folder, and menu.sh

mercifully.

can you do, with python3, one little visual interface dashboard, for windows & linux
for these aims. 

Upload Face Photo ( button 1 ) 
Searching.... from clarifai.com 
Responding requests.... from clarifai.com 

First name
Last name
Father's name
Mother's name
Member's name
Age
Gender
Nationality
Registered VAT number: if the persons, possess any bussiness.
Page Profiles. from pipl.com
Phone numbers. from pipl.com
Email numbers. from pipl.com 
Skype usernames.
Gmail usernames
Yahoo usernames


clarifai api's will helps. 

for the api key of clarifai. i will make clearly to the companies tv editions live for missing persons, that they to register in clarifai.com and to pay for the api key. 


to contact the person missing.

This hope from technology. only you will do. as the python3 scripter. 

do this parentaly hope. humanly hope. together from God, and with God.

and the documentation usage.

Windows

python3 clarifai.py 

create one shortcut target python3 clarifai.py to start web application with chrome, and firefox.
don't make for dashboard credential login.
in the dashboard, make clarifai key: 

face search
clarifai key

the data output in JSON, pdf, or excel. 
and for linux
Linux 

python3 clarifai.py 

An little interface dashboard software application based on python3 for web interfaces, offered for companies TV of the editions live, Europe&Albania, for missing persons. 

@harleo

**Comment by harleo** [comment]
@darknodi Sorry I can't fulfill special requests. Good luck.
