### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by astone75** [harleo/knockknock#9]
First of all thanks for your tool, there is now a compilation error because the dependency you use (goquery) has had a name change :
go get: github.com/puerkitobio/goquery@none updating to
        github.com/puerkitobio/goquery@v1.6.1: parsing go.mod:
        module declares its path as: github.com/PuerkitoBio/goquery
                but was required as: github.com/puerkitobio/goquery

Could you fix this in the project ?

Regards,

**Comment by harleo** [comment]
Hey @astone75,

thanks for reporting this issue! It should be resolved with the latest commit.
